/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function HeartModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/heartShape.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="exporting_layers">
        <mesh
          name="Curve001"
          castShadow
          receiveShadow
          geometry={nodes.Curve001.geometry}
          material={materials["Material.003"]}
          position={[10, 10, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/heartShape.gltf");
