/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF, useAnimations } from "@react-three/drei";

import React, { useRef, useEffect, useLayoutEffect } from "react";
import { Canvas, useFrame, useThree } from "react-three-fiber";
import gsap from "gsap";

import { ScrollTrigger } from "gsap/ScrollTrigger";

export function HeartModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/heartShape.gltf");
  const { actions } = useAnimations(animations, group);

  gsap.registerPlugin(ScrollTrigger);

  const mesh = useRef();
  const rotate2ModelsRef = props.rotate2ModelsRef;

  // scrolling effect
  useLayoutEffect(() => {
    gsap.timeline({
      scrollTrigger: {
        trigger: "#page-3",
        start: "top top",
        end: "bottom+=1000 bottom",
        pin: true,
        markers: true,
        scrub: true,
        delay: 2000,
        onEnter: () => {
          console.log("Animation started");
          //   document.getElementById("model-3").style.visibility = "visible";
        },
        onEnterBack: () => {
          // document.getElementById("model-2").style.visibility = "visible";
        },
        onLeave: () => {
          // document.getElementById("model-2").style.visibility = "hidden";
          // document.getElementById("page2").style.position = "fixed";
        },

        onLeaveBack: () => {
          // document.getElementById("model-2").style.visibility = "hidden";
        },
      },
    });
  });

  const rotationSpeed = 0.005;
  useFrame(() => {
    if (mesh.current) {
      mesh.current.rotation.y += rotationSpeed;
    }
  });

  return (
    <group {...props} dispose={null}>
      <group name="exporting_layers">
        <mesh
          ref={mesh}
          name="Curve001"
          castShadow
          receiveShadow
          geometry={nodes.Curve001.geometry}
          material={materials["Material.003"]}
          position={[10, 10, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/heartShape.gltf");
